import poolBrush1 from "../Images/pool-brush-1.webp"
import polarisP825 from "../Images/polaris-p825.webp"
import margaritaRing from "../Images/margarita-ring.jpg"
import unionConnector from "../Images/union-connector.jpg"
import raypakGasHeater from "../Images/raypak-gas-heater.jpg"
import chlorinePucks1 from "../Images/chlorine-pucks-1.png"
import abovegroundPool1 from "../Images/above-ground-pool-1.png"
import light1 from "../Images/light-1.jpg"
import multishock1 from "../Images/multishock-1.png"
import dolphinNautilus from "../Images/dolphin-nautilus.jpg"

export const data = [
        {
            _id: '1',
            name: '18" CURVED WALL BRUSH WITH ALUMINUM HANDLE',
            slug: '18-curved-wall-brush-with-aluminum-handle',
            category: 'Skimmers & Brushes',
            image: poolBrush1,
            price: 23.99,
            stockAmount: 15,
            brand: 'Ningbo',
            rating: 7.5,
            numOfReviews: 1,
            description: 'PVC kwik-fit handle',
        },
        {
            _id: '2',
            name: 'POLARIS P825 ROBOTIC IN GROUND POOL CLEANER WITH CADDY',
            slug: 'polaris-p825-robotic-in-ground-pool-cleaner-with-caddy',
            category: 'Robot Cleaners',
            image: polarisP825,
            price: 1299.00,
            stockAmount: 9,
            brand: 'Polaris',
            rating: 9.4,
            numOfReviews: 7,
            description: 'The Polaris P825 Robotic Cleaner delivers optimal cleaning performance for all in-ground pools surfaces',
        },
        {
            _id: '3',
            name: 'Swimline Margarita Ring',
            slug: 'swimline-margarita-ring',
            category: 'Loungers & Floats',
            image: margaritaRing,
            price: 52.99,
            stockAmount: 55,
            brand: 'Swimline',
            rating: 9.8,
            numOfReviews: 1,
            description: 'This float will get you in the summer mood!',
        },
        {
            _id: '4',
            name: 'Hayward SPX3200UNKIT Union Connector Replacement Kit',
            slug: 'union-kit',
            category: 'Parts',
            image: unionConnector,
            price: 75.64,
            stockAmount: 12,
            brand: 'Hayward',
            rating: 6.2,
            numOfReviews: 1,
            description: 'Hayward SPX3200UNKIT Union Connector Replacement Kit for Select Hayward Pumps and Heaters',
        },
        {
            _id: '5',
            name: 'Raypak P-R206A-MN Natural Gas Pool Heater 206k BTU (Millivolt)',
            slug: 'raypak-millivolt-natural-gas-heater-199k-btu',
            category: 'Heaters',
            image: raypakGasHeater,
            price: 2529.99,
            stockAmount: 5,
            brand: 'Raypak',
            rating: 9.8,
            numOfReviews: 4,
            description: 'Raypak 199k BTU Millivolt Nat. Gas Pool Heater',
        },
        {
            _id: '6',
            name: 'BEST SELLER King Size Chlorine Pucks Stabilized (6 Kg) by Pool Supplies Canada',
            slug: 'pool-supplies-canada-king-size-chlorine-pucks-6-kg',
            category: 'Chemicals',
            image: chlorinePucks1,
            price: 59.99,
            stockAmount: 37,
            brand: 'PoolSuppliesCanada',
            rating: 10.0,
            numOfReviews: 36,
            description: "Pool Supplies Canada's King Size Chlorine Pucks should be constantly dispensed into the pool in order to maintain proper sanitization levels.",
        },
        {
            _id: '7',
            name: 'Bestway Steel Pro Complete 13 ft 1 Inch x 6 ft 11 Inch Rectangular 32 Inch Tall Above Ground Pool Kit with Pump and Filter',
            slug: 'bestway-steel-pro-complete-13-ft-1-inch-x-6-ft-11-inch-rectangle-32-inch-tall-above-ground-pool-kit-with-pump-and-filter',
            category: 'Pool Kits',
            image: abovegroundPool1,
            price: 489.99,
            stockAmount: 3,
            brand: 'Bestway',
            rating: 6.4,
            numOfReviews: 7,
            description: 'Bestway Steel Pro Complete, pool walls are constructed with DuraPlus™, a material reinforced with a polyester mesh core and two layers of high gauge PVC for superior strength and durability.',
        },
        {
            _id: '8',
            name: 'Hayward Ignitor Kit Fd',
            slug: 'hayward-ignitor-kit-fd',
            category: 'Parts',
            image: light1,
            price: 99.99,
            stockAmount: 2,
            brand: 'Haward',
            rating: 6.9,
            numOfReviews: 1,
            description: 'The FDXLIGN1930 Hayward Ignitor Kit is suitable for replacement on Hayward models H150FDN, H150FDP, H200FDN, H200FDP, H250FDN, H250FDP, H300FDN, H300FDP, H350FDN, H350FDP, H400FDN, H400FD.',
        },
        {
            _id: '9',
            name: 'Maytronics Nautilus CC Plus Robotic Pool Cleaner',
            slug: 'maytronics-nautilus-cc-plus-robotic-pool-cleaner-w-wi-fi',
            category: 'Robot Cleaners',
            image: dolphinNautilus,
            price: 1099.99,
            stockAmount: 7,
            brand: 'Maytronics',
            rating: 8.3,
            numOfReviews: 12,
            description: 'Dolphin Nautilus CC is a brand new Maytronics cleaner that packs a variety of great features for a low price. It is a lightweight cleaner model with a powerful scrubbing brush that provides floor and wall coverage and an easy-to-access debris filter.',
        },
        {
            _id: '10',
            name: 'BEST SELLER Multi-Shock by Pool Supplies Canada (450 g)',
            slug: 'pool-supplies-canada-multi-shock-450-g',
            category: 'Chemicals',
            image: multishock1,
            price: 7.99,
            stockAmount: 72,
            brand: 'PoolSuppliesCanada',
            rating: 10.0,
            numOfReviews: 14,
            description: 'Pool Supplies Canada multi shock and conditioner is a fast acting, powerful shock treatment that produces crystal clear water and works in pools with all different surfaces.',
        },
];

export const category = [
    {
        id: 1,
        name: "Appetizer",
        urlParamName: 'appetizer',
    },
    {
        id: 2,
        name: "MO:MO",
        urlParamName: 'momo',
    },
    {
        id: 3,
        name: "Entree",
        urlParamName: 'entree',
    },
    {
        id: 4,
        name: "Drinks",
        urlParamName: 'drinks',
    },
    {
        id: 5,
        name: "Dessert",
        urlParamName: 'dessert',
    },
];